import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import stackWrapper from '../helper/api'
const Home = ({data}:{data:any}) => {
  console.log(data)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <img src={data?.section_8_promotional?.hero_image?.url} alt="Vercel Logo" width={200} height={200} />
    </div>
  )
}

export default Home


export const getServerSideProps = async (context:any) => {
  const data=  await stackWrapper.getHomePage('home_page', 'blt8b06eea0c35a7994')
  return {
   props: {
     data:data,
   },
 };
 }
